@MiniMES.Api_HostAddress = http://localhost:5062

GET {{MiniMES.Api_HostAddress}}/api/items
Accept: application/json

###

GET {{MiniMES.Api_HostAddress}}/api/items?search=ITEM
Accept: application/json

###

GET {{MiniMES.Api_HostAddress}}/api/items/1
Accept: application/json

###

POST {{MiniMES.Api_HostAddress}}/api/items
Content-Type: application/json

{
  "itemCode": "ITEM-002",
  "itemName": "Bracket A",
  "specification": "100x50",
  "unit": "EA",
  "itemType": "Product",
  "safetyStock": 20
}

###

PUT {{MiniMES.Api_HostAddress}}/api/items/1
Content-Type: application/json

{
  "itemName": "Test Item regenereated",
  "specification": "Sample",
  "unit": "EA",
  "itemType": "Product",
  "safetyStock": 15,
  "isActive": true
}

###

DELETE {{MiniMES.Api_HostAddress}}/api/items/1

###

GET {{MiniMES.Api_HostAddress}}/api/processes
Accept: application/json

###

GET {{MiniMES.Api_HostAddress}}/api/processes?search=CUT
Accept: application/json

###

GET {{MiniMES.Api_HostAddress}}/api/processes/1
Accept: application/json

###

POST {{MiniMES.Api_HostAddress}}/api/processes
Content-Type: application/json

{
  "processCode": "CUT",
  "processName": "Cutting",
  "description": "Raw material cutting process",
  "sortOrder": 10,
  "isInspection": false
}

###

POST {{MiniMES.Api_HostAddress}}/api/processes
Content-Type: application/json

{
  "processCode": "INSP",
  "processName": "Inspection",
  "description": "Final quality inspection",
  "sortOrder": 90,
  "isInspection": true
}

###

PUT {{MiniMES.Api_HostAddress}}/api/processes/1
Content-Type: application/json

{
  "processName": "Cutting Updated",
  "description": "Updated cutting process",
  "sortOrder": 10,
  "isInspection": false,
  "isActive": true
}

###

DELETE {{MiniMES.Api_HostAddress}}/api/processes/1

###
